use_frameworks!

platform :ios, '10.0'

target 'JMvvm_Example' do
  #pod 'JMvvm', :path => '../'
	pod 'JMvvm',:podspec => '../JMvvm.podspec'

  target 'JMvvm_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
